lTest = [
    "1",
    "2 * (1 + 3)",
    "tab",
    "tab[42]",
    "tab(42)",
    "sizeof(42)",
    "1 * 1",
    "tab++",
    "++tab",
    "tab->field",
    "tab->field.lol",
    "1 ? true : false",
    "tab[42](1 * 8)[RANGE]->subfield++",
    "tab[45][47]",
    "(char)tab",
    "lol = 1",
    "lol = 1 = 2 = 3",
]
